---
title: "HW3"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## GitHub Documents

This is an R Markdown for HW3. The previous file crashed during the uploading process. In this way, this one is a backup as required.

## Including Code

You can include R code in the document as follows:

```{r}
library(readr)
library(stringr)
gender <- read_csv("/Users/chenhaozhou/Desktop/gender.csv")

gender$Education <- str_replace(gender$Education, "Doctoral Degree", '5')
gender$Education <- str_replace(gender$Education, "Doctorate Degree", '4')
gender$Education <- str_replace(gender$Education, "Master's Degree", '3')
gender$Education <- str_replace(gender$Education, "Bachelor's Degree", '2')
gender$Education <- str_replace(gender$Education, "Associate's Degree", '1')

gender$Education <- as.numeric(gender$Education)
str(gender)


attach(gender)
#Get the Correlations between the measurements
cor(gender[c(2:6)])
# Using prcomp to compute the principal components (eigenvalues and eigenvectors). With scale=TRUE, variable means are set to zero, and variances set to one
gender_pca <- prcomp(gender[,-1],scale=TRUE)
summary(gender_pca)

(eigen_gender <- gender_pca$sdev^2)
names(eigen_gender) <- paste("PC",1:5,sep="")
eigen_gender
sumlambdas <- sum(eigen_gender)
sumlambdas
propvar <- eigen_gender/sumlambdas
propvar
cumvar_gender <- cumsum(propvar)
cumvar_gender
matlambdas <- rbind(eigen_gender,propvar,cumvar_gender)
rownames(matlambdas) <- c("Eigenvalues","Prop. variance","Cum. prop. variance")
round(matlambdas,4)
summary(gender_pca)
gender_pca$rotation
print(gender_pca)
## Sample scores stored in gender_pca$x
gender_pca$x
# Identifying the scores by their survival status
gendertyp_pca <- cbind(data.frame(gender),gender_pca$x)
gendertyp_pca
# Means of scores for all the PC's classified by their gender status
tabmeansPC <- aggregate(gendertyp_pca[,7:11],by=list(Gender=gender$Gender),mean)
tabmeansPC
tabmeansPC <- tabmeansPC[rev(order(tabmeansPC$Gender)),]
tabmeansPC
tabfmeans <- t(tabmeansPC[,-1])
tabfmeans
colnames(tabfmeans) <- t(as.vector(tabmeansPC[1]$Gender))
tabfmeans
# Standard deviations of scores for all the PC's classified by Survival status
tabsdsPC <- aggregate(gendertyp_pca[,7:11],by=list(Gender=gender$Gender),sd)
tabfsds <- t(tabsdsPC[,-1])
colnames(tabfsds) <- t(as.vector(tabsdsPC[1]$Gender))
tabfsds
t.test(PC1~gender$Gender,data=gendertyp_pca)
t.test(PC2~gender$Gender,data=gendertyp_pca)
t.test(PC3~gender$Gender,data=gendertyp_pca)
t.test(PC4~gender$Gender,data=gendertyp_pca)
t.test(PC5~gender$Gender,data=gendertyp_pca)
## F ratio tests
var.test(PC1~gender$Gender,data=gendertyp_pca)
var.test(PC2~gender$Gender,data=gendertyp_pca)
var.test(PC3~gender$Gender,data=gendertyp_pca)
var.test(PC4~gender$Gender,data=gendertyp_pca)
var.test(PC5~gender$Gender,data=gendertyp_pca)
# Levene's tests (one-sided)
library(car)
(LTPC1 <- leveneTest(PC1~gender$Gender,data=gendertyp_pca))
(p_PC1_1sided <- LTPC1[[3]][1]/2)
(LTPC2 <- leveneTest(PC2~gender$Gender,data=gendertyp_pca))
(p_PC2_1sided=LTPC2[[3]][1]/2)
(LTPC3 <- leveneTest(PC3~gender$Gender,data=gendertyp_pca))
(p_PC3_1sided <- LTPC3[[3]][1]/2)
(LTPC4 <- leveneTest(PC4~gender$Gender,data=gendertyp_pca))
(p_PC4_1sided <- LTPC4[[3]][1]/2)
(LTPC5 <- leveneTest(PC5~gender$Gender,data=gendertyp_pca))
(p_PC5_1sided <- LTPC5[[3]][1]/2)
# Plotting the scores for the first and second components
plot(gendertyp_pca$PC1, gendertyp_pca$PC2,pch=ifelse(gendertyp_pca$Gender == "S",1,16),xlab="PC1", ylab="PC2", main="131 gender against values for PC1 & PC2")
abline(h=0)
abline(v=0)
legend("bottomleft", legend=c("Survivor","Nonsurvivor"), pch=c(1,16))
plot(eigen_gender, xlab = "Component number", ylab = "Component variance", type = "l", main = "Scree diagram")
plot(log(eigen_gender), xlab = "Component number",ylab = "log(Component variance)", type="l",main = "Log(eigenvalue) diagram")
print(summary(gender_pca))
diag(cov(gender_pca$x))
xlim <- range(gender_pca$x[,1])
gender_pca$x[,1]
gender_pca$x
plot(gender_pca$x,xlim=xlim,ylim=xlim)
gender_pca$rotation[,1]
gender_pca$rotation
plot(gender[,-1])
gender_pca$x
plot(gender_pca)
#get the original value of the data based on PCA
center <- gender_pca$center
scale <- gender_pca$scale
new_gender <- as.matrix(gender[,-1])
new_gender
drop(scale(new_gender,center=center, scale=scale)%*%gender_pca$rotation[,1])
predict(gender_pca)[,1]
#The aboved two gives us the same thing. predict is a good function to know.
gender$Gender <- as.factor(gender$Gender)
out <- sapply(1:5, function(i){plot(gender$Gender,gender_pca$x[,i],xlab=paste("PC",i,sep=""),ylab="gender")})
pairs(gender_pca$x[,1:5], ylim = c(-6,4),xlim = c(-6,4),panel=function(x,y,...){text(x,y,gender$Gender)})

# Better Ways to Visualize
library(factoextra)
library(FactoMineR)
library(ggfortify)
library(psych)
library(corrplot)
library(devtools)

# Correlation
pairs.panels(gender[,-1],
             gap = 0,
             bg = c("red", "blue")[gender$Gender],
             pch=21)

pairs.panels(gender_pca$x,
             gap=0,
             bg = c("red", "blue")[gender$Gender],
             pch=21)




fviz_eig(gender_pca, addlabels = TRUE)
fviz_pca_var(gender_pca,col.var = "cos2",
             gradient.cols = c("#FFCC00", "#CC9933", "#660033", "#330033"),
             repel = TRUE)
fviz_pca_ind(gender_pca, col.ind = "cos2", 
                  gradient.cols = c("#FFCC00", "#CC9933", "#660033", "#330033"), 
                  repel = TRUE)
biplot(gender_pca)
autoplot(gender_pca,
         data = gender[,-1],
         loadings = TRUE,
         labels = gender$Gender)

# Different PCA Method. 
res.pca <- PCA(gender[,-1], graph = FALSE)
print(res.pca)

# Visualize and Interpret PCA using these functions 

#get_eigenvalue(res.pca): Extract the eigenvalues/variances of principal components
#fviz_eig(res.pca): Visualize the eigenvalues
#get_pca_ind(res.pca), get_pca_var(res.pca): Extract the results for individuals and variables, respectively.
#fviz_pca_ind(res.pca), fviz_pca_var(res.pca): Visualize the results individuals and variables, respectively.
#fviz_pca_biplot(res.pca): Make a biplot of individuals and variables.

eig.val <- get_eigenvalue(res.pca)
eig.val

fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 50))

var <- get_pca_var(res.pca)
#var$coord: coordinates of variables to create a scatter plot
#var$cos2: represents the quality of representation for variables on the factor map. It’s calculated as the squared coordinates: var.cos2 = var.coord * var.coord.
#var$contrib: contains the contributions (in percentage) of the variables to the principal components. 
#The contribution of a variable (var) to a given principal component is (in percentage) : (var.cos2 * 100) / (total cos2 of the component).
var

# Coordinates
head(var$coord)
# Cos2: quality on the factore map
head(var$cos2)
# Contributions to the principal components
head(var$contrib)

#The plot Below is also known as variable correlation plots. It shows the relationships between all variables. It can be interpreted as follow:

#Positively correlated variables are grouped together.
#Negatively correlated variables are positioned on opposite sides of the plot origin (opposed quadrants).
#The distance between variables and the origin measures the quality of the variables on the factor map. 
#Variables that are away from the origin are well represented on the factor map.

# Correlation circle
fviz_pca_var(res.pca, col.var = "black")

# Quality of representation


corrplot(var$cos2, is.corr=FALSE)
# Total cos2 of variables on Dim.1 and Dim.2
#A high cos2 indicates a good representation of the variable on the principal component. 
#In this case the variable is positioned close to the circumference of the correlation circle.
#A low cos2 indicates that the variable is not perfectly represented by the PCs. 
#In this case the variable is close to the center of the circle.

fviz_cos2(res.pca, choice = "var", axes = 1:2)
fviz_pca_var(res.pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )
# Change the transparency by cos2 values
fviz_pca_var(res.pca, alpha.var = "cos2")
corrplot(var$contrib, is.corr=FALSE)
# Contributions of variables to PC1
fviz_contrib(res.pca, choice = "var", axes = 1, top = 10)
# Contributions of variables to PC2
fviz_contrib(res.pca, choice = "var", axes = 2, top = 10)
fviz_pca_var(res.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
             )
fviz_pca_var(res.pca, alpha.var = "contrib")

fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = gender$Gender, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )


# Description of PC

res.desc <- dimdesc(res.pca, axes = c(1,2,3,4,5), proba = 0.05)
# Description of dimension 1
res.desc$Dim.1
res.desc$Dim.2
res.desc$Dim.3
res.desc$Dim.4
res.desc$Dim.5

# Graph of Indiviuals
ind <- get_pca_ind(res.pca)
ind

## Principal Component Analysis Results for individuals
##  ===================================================
##   Name       Description                       
## 1 "$coord"   "Coordinates for the individuals" 
## 2 "$cos2"    "Cos2 for the individuals"        
## 3 "$contrib" "contributions of the individuals"
#To get access to the different components, use this:

# Coordinates of individuals
head(ind$coord)
# Quality of individuals
head(ind$cos2)
# Contributions of individuals
head(ind$contrib)

fviz_pca_ind(res.pca)

fviz_pca_ind(res.pca, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )
fviz_pca_ind(res.pca, pointsize = "cos2", 
             pointshape = 68, fill = "#E7B800",
             repel = TRUE # Avoid text overlapping (slow if many points)
             )

fviz_pca_ind(res.pca, col.ind = "cos2", pointsize = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )
fviz_cos2(res.pca, choice = "ind")
# Total contribution on PC1 and PC2
fviz_contrib(res.pca, choice = "ind", axes = 1:2)

# Create a random continuous variable of length 23,
# Same length as the number of active individuals in the PCA
set.seed(123)
my.cont.var <- rnorm(131)
# Color individuals by the continuous variable
fviz_pca_ind(res.pca, col.ind = my.cont.var,
             gradient.cols = c("blue", "yellow", "red"),
             legend.title = "Cont.Var")

fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = gender$Gender, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )

fviz_pca_ind(res.pca, geom.ind = "point", col.ind = gender$Gender, 
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, ellipse.type = "confidence",
             legend.title = "Groups"
             )
fviz_pca_ind(res.pca,
             label = "none", # hide individual labels
             habillage = gender$Gender, # color by groups
             addEllipses = TRUE, # Concentration ellipses
             palette = "jco"
             )
fviz_pca_var(res.pca, geom.var = c("point", "text"))
# Show individuals text labels only
fviz_pca_ind(res.pca, geom.ind =  "text")
# Change the size of arrows an labels
fviz_pca_var(res.pca, arrowsize = 1, labelsize = 5, 
             repel = TRUE)
# Change points size, shape and fill color
# Change labelsize
fviz_pca_ind(res.pca, 
             pointsize = 3, pointshape = 21, fill = "lightblue",
             labelsize = 5, repel = TRUE)

fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (but not "text")
             group.ind = gender$Gender, # color by groups
             legend.title = "Groups",
             mean.point = FALSE)
fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (but not "text")
             group.ind = gender$Gender, # color by groups
             legend.title = "Groups",
             mean.point = TRUE)
fviz_pca_var(res.pca, axes.linetype = "blank")



ind.p <- fviz_pca_ind(res.pca, geom = "point", col.ind = gender$Gender)
ggpubr::ggpar(ind.p,
              title = "Principal Component Analysis",
              subtitle = "Iris data set",
              caption = "Source: factoextra",
              xlab = "PC1", ylab = "PC2",
              legend.title = "gender", legend.position = "top",
              ggtheme = theme_gray(), palette = "jco"
              )

fviz_pca_biplot(res.pca, repel = TRUE,col.ind = gender$Gender,
                col.var = "#2E9FDF", # Variables color
                )

fviz_pca_biplot(res.pca, 
                col.ind = gender$Gender, palette = "jco", 
                addEllipses = TRUE, label = "var",
                col.var = "black", repel = TRUE,
                legend.title = "gender") 

fviz_pca_biplot(res.pca, 
                # Fill individuals by groups
                geom.ind = "point",
                pointshape = 21,
                pointsize = 2.5,
                fill.ind = gender$Gender,
                col.ind = "black",
                # Color variable by groups
                legend.title = list(fill = "gender", color = "Clusters"),
                repel = TRUE        # Avoid label overplotting
             )+
  ggpubr::fill_palette("jco")+      # Indiviual fill color
  ggpubr::color_palette("npg")      # Variable colors

fviz_pca_biplot(res.pca, 
                # Individuals
                geom.ind = "point",
                fill.ind = gender$Gender, col.ind = "black",
                pointshape = 21, pointsize = 2,
                palette = "jco",
                addEllipses = TRUE,
                # Variables
                alpha.var ="contrib", col.var = "contrib",
                gradient.cols = "RdYlBu",
                legend.title = list(fill = "gender", color = "Contrib",
                                    alpha = "Contrib")
                )
```


## Including Plots


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
















